language: php
php:
  - '5.3'
  - '7.0'

# blacklist
branches:
  except:
    # master has no active development on it
    - master
	- DemoServer
	- TrialServer

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # create mysql database
  - mysql -e "DROP DATABASE IF EXISTS x2engine; CREATE DATABASE x2engine;" -u root;

  #install x2crm
  - cp build/constants.php x2engine/constants.php
  - cp build/installConfig.php x2engine/installConfig.php
  - php x2engine/initialize.php silent

# run tests
script: 
  # unit tests
  - phpunit --configuration build/phpunit_unit.xml x2engine/protected/tests/unit
  # functional tests
  #- phpunit --configuration build/phpunit_functional.xml x2engine/protected/tests/functional


