language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

# blacklist
branches:
  only:
    - jake_travis_ci 

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - pear install phpunit/PHPUnit_Selenium
  - phpenv rehash
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # configure php ini file
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'allow_url_fopen = on' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart

  # create mysql database
  - mysql -e "DROP DATABASE IF EXISTS x2engine; CREATE DATABASE x2engine;" -u root;

  #install x2crm
  - cp build/constants.php x2engine/constants.php
  - cp build/installConfig.php x2engine/installConfig.php
  - cd x2engine && php initialize.php silent && cd ..

  #configure tests
  - cp build/WebTestConfig.php x2engine/protected/tests/WebTestConfig.php

# run tests
script: 
  # unit tests
  - phpunit --configuration build/phpunit_unit.xml x2engine/protected/tests/unit
  # functional tests
  #- phpunit --configuration build/phpunit_functional.xml x2engine/protected/tests/functional

after_script:
  # capture apache error log
  - sudo cat /var/log/apache2/error.log
